// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/app_router.proto

package approuterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AppRouter_Open_FullMethodName = "/approuter.v1.AppRouter/Open"
)

// AppRouterClient is the client API for AppRouter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AppRouter defines the bidirectional stream used by apps to interact with the node.
type AppRouterClient interface {
	Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppFrame, AppFrame], error)
}

type appRouterClient struct {
	cc grpc.ClientConnInterface
}

func NewAppRouterClient(cc grpc.ClientConnInterface) AppRouterClient {
	return &appRouterClient{cc}
}

func (c *appRouterClient) Open(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppFrame, AppFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AppRouter_ServiceDesc.Streams[0], AppRouter_Open_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppFrame, AppFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppRouter_OpenClient = grpc.BidiStreamingClient[AppFrame, AppFrame]

// AppRouterServer is the server API for AppRouter service.
// All implementations must embed UnimplementedAppRouterServer
// for forward compatibility.
//
// AppRouter defines the bidirectional stream used by apps to interact with the node.
type AppRouterServer interface {
	Open(grpc.BidiStreamingServer[AppFrame, AppFrame]) error
	mustEmbedUnimplementedAppRouterServer()
}

// UnimplementedAppRouterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAppRouterServer struct{}

func (UnimplementedAppRouterServer) Open(grpc.BidiStreamingServer[AppFrame, AppFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Open not implemented")
}
func (UnimplementedAppRouterServer) mustEmbedUnimplementedAppRouterServer() {}
func (UnimplementedAppRouterServer) testEmbeddedByValue()                   {}

// UnsafeAppRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppRouterServer will
// result in compilation errors.
type UnsafeAppRouterServer interface {
	mustEmbedUnimplementedAppRouterServer()
}

func RegisterAppRouterServer(s grpc.ServiceRegistrar, srv AppRouterServer) {
	// If the following call pancis, it indicates UnimplementedAppRouterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AppRouter_ServiceDesc, srv)
}

func _AppRouter_Open_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppRouterServer).Open(&grpc.GenericServerStream[AppFrame, AppFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AppRouter_OpenServer = grpc.BidiStreamingServer[AppFrame, AppFrame]

// AppRouter_ServiceDesc is the grpc.ServiceDesc for AppRouter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppRouter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "approuter.v1.AppRouter",
	HandlerType: (*AppRouterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Open",
			Handler:       _AppRouter_Open_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/app_router.proto",
}
