// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/app_router.proto

package approuterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AppFrame is the envelope exchanged over the Open stream.
type AppFrame struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// correlation_id lets clients tie responses to requests when needed.
	CorrelationId string `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	// Types that are assignable to Body:
	//	*AppFrame_Connect
	//	*AppFrame_ConnectAck
	//	*AppFrame_StartChat
	//	*AppFrame_StartChatAck
	//	*AppFrame_ChatMessage
	//	*AppFrame_ChatMessageAck
	//	*AppFrame_DeleteChat
	//	*AppFrame_DeleteChatAck
	//	*AppFrame_Error
	//	*AppFrame_Heartbeat
	//	*AppFrame_FindApp
	//	*AppFrame_FindAppResult
	Body isAppFrame_Body `protobuf_oneof:"body"`
}

func (x *AppFrame) Reset() {
	*x = AppFrame{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppFrame) ProtoMessage() {}

func (x *AppFrame) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppFrame.ProtoReflect.Descriptor instead.
func (*AppFrame) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{0}
}

func (x *AppFrame) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (m *AppFrame) GetBody() isAppFrame_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *AppFrame) GetConnect() *Connect {
	if x, ok := x.GetBody().(*AppFrame_Connect); ok {
		return x.Connect
	}
	return nil
}

func (x *AppFrame) GetConnectAck() *ConnectAck {
	if x, ok := x.GetBody().(*AppFrame_ConnectAck); ok {
		return x.ConnectAck
	}
	return nil
}

func (x *AppFrame) GetStartChat() *StartChat {
	if x, ok := x.GetBody().(*AppFrame_StartChat); ok {
		return x.StartChat
	}
	return nil
}

func (x *AppFrame) GetStartChatAck() *StartChatAck {
	if x, ok := x.GetBody().(*AppFrame_StartChatAck); ok {
		return x.StartChatAck
	}
	return nil
}

func (x *AppFrame) GetChatMessage() *ChatMessage {
	if x, ok := x.GetBody().(*AppFrame_ChatMessage); ok {
		return x.ChatMessage
	}
	return nil
}

func (x *AppFrame) GetChatMessageAck() *ChatMessageAck {
	if x, ok := x.GetBody().(*AppFrame_ChatMessageAck); ok {
		return x.ChatMessageAck
	}
	return nil
}

func (x *AppFrame) GetDeleteChat() *DeleteChat {
	if x, ok := x.GetBody().(*AppFrame_DeleteChat); ok {
		return x.DeleteChat
	}
	return nil
}

func (x *AppFrame) GetDeleteChatAck() *DeleteChatAck {
	if x, ok := x.GetBody().(*AppFrame_DeleteChatAck); ok {
		return x.DeleteChatAck
	}
	return nil
}

func (x *AppFrame) GetError() *Error {
	if x, ok := x.GetBody().(*AppFrame_Error); ok {
		return x.Error
	}
	return nil
}

func (x *AppFrame) GetHeartbeat() *Heartbeat {
	if x, ok := x.GetBody().(*AppFrame_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (x *AppFrame) GetFindApp() *FindApp {
	if x, ok := x.GetBody().(*AppFrame_FindApp); ok {
		return x.FindApp
	}
	return nil
}

func (x *AppFrame) GetFindAppResult() *FindAppResult {
	if x, ok := x.GetBody().(*AppFrame_FindAppResult); ok {
		return x.FindAppResult
	}
	return nil
}

type isAppFrame_Body interface {
	isAppFrame_Body()
}

type AppFrame_Connect struct {
	Connect *Connect `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type AppFrame_ConnectAck struct {
	ConnectAck *ConnectAck `protobuf:"bytes,3,opt,name=connect_ack,json=connectAck,proto3,oneof"`
}

type AppFrame_StartChat struct {
	StartChat *StartChat `protobuf:"bytes,4,opt,name=start_chat,json=startChat,proto3,oneof"`
}

type AppFrame_StartChatAck struct {
	StartChatAck *StartChatAck `protobuf:"bytes,5,opt,name=start_chat_ack,json=startChatAck,proto3,oneof"`
}

type AppFrame_ChatMessage struct {
	ChatMessage *ChatMessage `protobuf:"bytes,6,opt,name=chat_message,json=chatMessage,proto3,oneof"`
}

type AppFrame_ChatMessageAck struct {
	ChatMessageAck *ChatMessageAck `protobuf:"bytes,7,opt,name=chat_message_ack,json=chatMessageAck,proto3,oneof"`
}

type AppFrame_DeleteChat struct {
	DeleteChat *DeleteChat `protobuf:"bytes,8,opt,name=delete_chat,json=deleteChat,proto3,oneof"`
}

type AppFrame_DeleteChatAck struct {
	DeleteChatAck *DeleteChatAck `protobuf:"bytes,9,opt,name=delete_chat_ack,json=deleteChatAck,proto3,oneof"`
}

type AppFrame_Error struct {
	Error *Error `protobuf:"bytes,10,opt,name=error,proto3,oneof"`
}

type AppFrame_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AppFrame_FindApp struct {
	FindApp *FindApp `protobuf:"bytes,12,opt,name=find_app,json=findApp,proto3,oneof"`
}

type AppFrame_FindAppResult struct {
	FindAppResult *FindAppResult `protobuf:"bytes,13,opt,name=find_app_result,json=findAppResult,proto3,oneof"`
}

func (*AppFrame_Connect) isAppFrame_Body() {}

func (*AppFrame_ConnectAck) isAppFrame_Body() {}

func (*AppFrame_StartChat) isAppFrame_Body() {}

func (*AppFrame_StartChatAck) isAppFrame_Body() {}

func (*AppFrame_ChatMessage) isAppFrame_Body() {}

func (*AppFrame_ChatMessageAck) isAppFrame_Body() {}

func (*AppFrame_DeleteChat) isAppFrame_Body() {}

func (*AppFrame_DeleteChatAck) isAppFrame_Body() {}

func (*AppFrame_Error) isAppFrame_Body() {}

func (*AppFrame_Heartbeat) isAppFrame_Body() {}

func (*AppFrame_FindApp) isAppFrame_Body() {}

func (*AppFrame_FindAppResult) isAppFrame_Body() {}

// Connect is the initial handshake frame from an app.
type Connect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppPublicKey []byte            `protobuf:"bytes,1,opt,name=app_public_key,json=appPublicKey,proto3" json:"app_public_key,omitempty"`
	Signature    []byte            `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	NodeId       string            `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata     map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Connect) Reset() {
	*x = Connect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Connect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Connect) ProtoMessage() {}

func (x *Connect) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Connect.ProtoReflect.Descriptor instead.
func (*Connect) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{1}
}

func (x *Connect) GetAppPublicKey() []byte {
	if x != nil {
		return x.AppPublicKey
	}
	return nil
}

func (x *Connect) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *Connect) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Connect) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ConnectAck confirms a successful connection/authentication.
type ConnectAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignedSessionId string `protobuf:"bytes,1,opt,name=assigned_session_id,json=assignedSessionId,proto3" json:"assigned_session_id,omitempty"`
}

func (x *ConnectAck) Reset() {
	*x = ConnectAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectAck) ProtoMessage() {}

func (x *ConnectAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectAck.ProtoReflect.Descriptor instead.
func (*ConnectAck) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{2}
}

func (x *ConnectAck) GetAssignedSessionId() string {
	if x != nil {
		return x.AssignedSessionId
	}
	return ""
}

// StartChat initiates a chat with a peer connected to the same node.
type StartChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId                   string            `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	LocalEphemeralPublicKey  []byte            `protobuf:"bytes,2,opt,name=local_ephemeral_public_key,json=localEphemeralPublicKey,proto3" json:"local_ephemeral_public_key,omitempty"`
	Signature                []byte            `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	Metadata                 map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TargetAppId              string            `protobuf:"bytes,5,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	TargetNodeHint           string            `protobuf:"bytes,6,opt,name=target_node_hint,json=targetNodeHint,proto3" json:"target_node_hint,omitempty"`
	LocalEphemeralPrivateKey []byte            `protobuf:"bytes,7,opt,name=local_ephemeral_private_key,json=localEphemeralPrivateKey,proto3" json:"local_ephemeral_private_key,omitempty"`
	KeyVersion               uint32            `protobuf:"varint,8,opt,name=key_version,json=keyVersion,proto3" json:"key_version,omitempty"`
	HkdfSalt                 []byte            `protobuf:"bytes,9,opt,name=hkdf_salt,json=hkdfSalt,proto3" json:"hkdf_salt,omitempty"`
	HkdfInfo                 string            `protobuf:"bytes,10,opt,name=hkdf_info,json=hkdfInfo,proto3" json:"hkdf_info,omitempty"`
	Rekey                    bool              `protobuf:"varint,11,opt,name=rekey,proto3" json:"rekey,omitempty"`
}

func (x *StartChat) Reset() {
	*x = StartChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChat) ProtoMessage() {}

func (x *StartChat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChat.ProtoReflect.Descriptor instead.
func (*StartChat) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{3}
}

func (x *StartChat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *StartChat) GetLocalEphemeralPublicKey() []byte {
	if x != nil {
		return x.LocalEphemeralPublicKey
	}
	return nil
}

func (x *StartChat) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *StartChat) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *StartChat) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *StartChat) GetTargetNodeHint() string {
	if x != nil {
		return x.TargetNodeHint
	}
	return ""
}

func (x *StartChat) GetLocalEphemeralPrivateKey() []byte {
	if x != nil {
		return x.LocalEphemeralPrivateKey
	}
	return nil
}

func (x *StartChat) GetKeyVersion() uint32 {
	if x != nil {
		return x.KeyVersion
	}
	return 0
}

func (x *StartChat) GetHkdfSalt() []byte {
	if x != nil {
		return x.HkdfSalt
	}
	return nil
}

func (x *StartChat) GetHkdfInfo() string {
	if x != nil {
		return x.HkdfInfo
	}
	return ""
}

func (x *StartChat) GetRekey() bool {
	if x != nil {
		return x.Rekey
	}
	return false
}

// StartChatAck acknowledges chat initialization.
type StartChatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
}

func (x *StartChatAck) Reset() {
	*x = StartChatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChatAck) ProtoMessage() {}

func (x *StartChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChatAck.ProtoReflect.Descriptor instead.
func (*StartChatAck) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{4}
}

func (x *StartChatAck) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

// ChatMessage carries encrypted payloads between peers.
type ChatMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId   string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Payload  []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Sequence uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{5}
}

func (x *ChatMessage) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatMessage) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// ChatMessageAck acknowledges receipt of a chat payload.
type ChatMessageAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId   string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Sequence uint64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
}

func (x *ChatMessageAck) Reset() {
	*x = ChatMessageAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChatMessageAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessageAck) ProtoMessage() {}

func (x *ChatMessageAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessageAck.ProtoReflect.Descriptor instead.
func (*ChatMessageAck) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{6}
}

func (x *ChatMessageAck) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *ChatMessageAck) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// DeleteChat requests teardown of chat state and key erasure.
type DeleteChat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Reason string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *DeleteChat) Reset() {
	*x = DeleteChat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChat) ProtoMessage() {}

func (x *DeleteChat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChat.ProtoReflect.Descriptor instead.
func (*DeleteChat) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteChat) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteChat) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DeleteChatAck confirms chat teardown.
type DeleteChatAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChatId string `protobuf:"bytes,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DeleteChatAck) Reset() {
	*x = DeleteChatAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteChatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatAck) ProtoMessage() {}

func (x *DeleteChatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatAck.ProtoReflect.Descriptor instead.
func (*DeleteChatAck) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteChatAck) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *DeleteChatAck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Heartbeat keeps the stream active and allows liveness tracking.
type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TimestampNanos int64 `protobuf:"varint,1,opt,name=timestamp_nanos,json=timestampNanos,proto3" json:"timestamp_nanos,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{9}
}

func (x *Heartbeat) GetTimestampNanos() int64 {
	if x != nil {
		return x.TimestampNanos
	}
	return 0
}

// FindApp requests the hosting node for a target app identity.
type FindApp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetAppId    string `protobuf:"bytes,1,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	TargetNodeHint string `protobuf:"bytes,2,opt,name=target_node_hint,json=targetNodeHint,proto3" json:"target_node_hint,omitempty"`
}

func (x *FindApp) Reset() {
	*x = FindApp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindApp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindApp) ProtoMessage() {}

func (x *FindApp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindApp.ProtoReflect.Descriptor instead.
func (*FindApp) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{10}
}

func (x *FindApp) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *FindApp) GetTargetNodeHint() string {
	if x != nil {
		return x.TargetNodeHint
	}
	return ""
}

// FindAppResult returns routing information for a target app.
type FindAppResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetAppId string `protobuf:"bytes,1,opt,name=target_app_id,json=targetAppId,proto3" json:"target_app_id,omitempty"`
	NodeId      string `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status      string `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *FindAppResult) Reset() {
	*x = FindAppResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FindAppResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAppResult) ProtoMessage() {}

func (x *FindAppResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAppResult.ProtoReflect.Descriptor instead.
func (*FindAppResult) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{11}
}

func (x *FindAppResult) GetTargetAppId() string {
	if x != nil {
		return x.TargetAppId
	}
	return ""
}

func (x *FindAppResult) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FindAppResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// Error communicates terminal stream issues.
type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_app_router_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_app_router_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_app_router_proto_rawDescGZIP(), []int{12}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_app_router_proto protoreflect.FileDescriptor

var file_proto_app_router_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x70, 0x5f, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0x96, 0x06, 0x0a, 0x08, 0x41, 0x70, 0x70, 0x46, 0x72,
	0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x72, 0x72, 0x65, 0x6c, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x6f, 0x72,
	0x72, 0x65, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x61, 0x70,
	0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x48, 0x00, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x3b, 0x0a,
	0x0b, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0a,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x43, 0x68, 0x61, 0x74, 0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x43, 0x68, 0x61, 0x74, 0x12, 0x42, 0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x63, 0x68,
	0x61, 0x74, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0c, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x43, 0x68, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x3e, 0x0a, 0x0c, 0x63, 0x68, 0x61, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x68,
	0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x48, 0x00, 0x52, 0x0b, 0x63, 0x68, 0x61,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x48, 0x0a, 0x10, 0x63, 0x68, 0x61, 0x74,
	0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b,
	0x48, 0x00, 0x52, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41,
	0x63, 0x6b, 0x12, 0x3b, 0x0a, 0x0b, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61,
	0x74, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x12,
	0x45, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x61,
	0x63, 0x6b, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68,
	0x61, 0x74, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x0d, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43,
	0x68, 0x61, 0x74, 0x41, 0x63, 0x6b, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x37, 0x0a, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x48,
	0x00, 0x52, 0x09, 0x68, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x32, 0x0a, 0x08,
	0x66, 0x69, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69,
	0x6e, 0x64, 0x41, 0x70, 0x70, 0x48, 0x00, 0x52, 0x07, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x70, 0x70,
	0x12, 0x45, 0x0a, 0x0f, 0x66, 0x69, 0x6e, 0x64, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x70, 0x70, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x70, 0x70,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x66, 0x69, 0x6e, 0x64, 0x41, 0x70,
	0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22,
	0xe4, 0x01, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x24, 0x0a, 0x0e, 0x61,
	0x70, 0x70, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0c, 0x61, 0x70, 0x70, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x61, 0x70, 0x70,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x3c, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x41, 0x63, 0x6b, 0x12, 0x2e, 0x0a, 0x13, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64,
	0x5f, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x11, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0xfd, 0x03, 0x0a, 0x09, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68,
	0x61, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x3b, 0x0a, 0x1a, 0x6c,
	0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x17, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67,
	0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x41, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f,
	0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x28, 0x0a,
	0x10, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x69, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e,
	0x6f, 0x64, 0x65, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x1b, 0x6c, 0x6f, 0x63, 0x61, 0x6c,
	0x5f, 0x65, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x76, 0x61,
	0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x18, 0x6c, 0x6f,
	0x63, 0x61, 0x6c, 0x45, 0x70, 0x68, 0x65, 0x6d, 0x65, 0x72, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x76,
	0x61, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x6b, 0x65, 0x79, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6b, 0x65, 0x79,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6b, 0x64, 0x66, 0x5f,
	0x73, 0x61, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x68, 0x6b, 0x64, 0x66,
	0x53, 0x61, 0x6c, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x68, 0x6b, 0x64, 0x66, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6b, 0x64, 0x66, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x6b, 0x65, 0x79, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x05, 0x72, 0x65, 0x6b, 0x65, 0x79, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x3a, 0x02, 0x38, 0x01, 0x22, 0x27, 0x0a, 0x0c, 0x53, 0x74, 0x61, 0x72, 0x74, 0x43, 0x68, 0x61,
	0x74, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x22, 0x5c, 0x0a,
	0x0b, 0x43, 0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x22, 0x45, 0x0a, 0x0e, 0x43,
	0x68, 0x61, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a,
	0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x73, 0x65, 0x71, 0x75, 0x65, 0x6e,
	0x63, 0x65, 0x22, 0x3d, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x22, 0x40, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x43, 0x68, 0x61, 0x74, 0x41,
	0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x68, 0x61, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x34, 0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74,
	0x12, 0x27, 0x0a, 0x0f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x5f, 0x6e, 0x61,
	0x6e, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x22, 0x57, 0x0a, 0x07, 0x46, 0x69, 0x6e,
	0x64, 0x41, 0x70, 0x70, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61,
	0x70, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x69,
	0x6e, 0x74, 0x22, 0x64, 0x0a, 0x0d, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x12, 0x22, 0x0a, 0x0d, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x5f, 0x61, 0x70,
	0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x35, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32,
	0x47, 0x0a, 0x09, 0x41, 0x70, 0x70, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a, 0x04,
	0x4f, 0x70, 0x65, 0x6e, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x61,
	0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x70, 0x70, 0x46,
	0x72, 0x61, 0x6d, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x70, 0x72,
	0x6f, 0x78, 0x79, 0x2f, 0x68, 0x65, 0x72, 0x6d, 0x65, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x78, 0x79,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74,
	0x65, 0x72, 0x70, 0x62, 0x3b, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_app_router_proto_rawDescOnce sync.Once
	file_proto_app_router_proto_rawDescData = file_proto_app_router_proto_rawDesc
)

func file_proto_app_router_proto_rawDescGZIP() []byte {
	file_proto_app_router_proto_rawDescOnce.Do(func() {
		file_proto_app_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_app_router_proto_rawDescData)
	})
	return file_proto_app_router_proto_rawDescData
}

var file_proto_app_router_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_app_router_proto_goTypes = []interface{}{
	(*AppFrame)(nil),       // 0: approuter.v1.AppFrame
	(*Connect)(nil),        // 1: approuter.v1.Connect
	(*ConnectAck)(nil),     // 2: approuter.v1.ConnectAck
	(*StartChat)(nil),      // 3: approuter.v1.StartChat
	(*StartChatAck)(nil),   // 4: approuter.v1.StartChatAck
	(*ChatMessage)(nil),    // 5: approuter.v1.ChatMessage
	(*ChatMessageAck)(nil), // 6: approuter.v1.ChatMessageAck
	(*DeleteChat)(nil),     // 7: approuter.v1.DeleteChat
	(*DeleteChatAck)(nil),  // 8: approuter.v1.DeleteChatAck
	(*Heartbeat)(nil),      // 9: approuter.v1.Heartbeat
	(*FindApp)(nil),        // 10: approuter.v1.FindApp
	(*FindAppResult)(nil),  // 11: approuter.v1.FindAppResult
	(*Error)(nil),          // 12: approuter.v1.Error
	nil,                    // 13: approuter.v1.Connect.MetadataEntry
	nil,                    // 14: approuter.v1.StartChat.MetadataEntry
}
var file_proto_app_router_proto_depIdxs = []int32{
	1,  // 0: approuter.v1.AppFrame.connect:type_name -> approuter.v1.Connect
	2,  // 1: approuter.v1.AppFrame.connect_ack:type_name -> approuter.v1.ConnectAck
	3,  // 2: approuter.v1.AppFrame.start_chat:type_name -> approuter.v1.StartChat
	4,  // 3: approuter.v1.AppFrame.start_chat_ack:type_name -> approuter.v1.StartChatAck
	5,  // 4: approuter.v1.AppFrame.chat_message:type_name -> approuter.v1.ChatMessage
	6,  // 5: approuter.v1.AppFrame.chat_message_ack:type_name -> approuter.v1.ChatMessageAck
	7,  // 6: approuter.v1.AppFrame.delete_chat:type_name -> approuter.v1.DeleteChat
	8,  // 7: approuter.v1.AppFrame.delete_chat_ack:type_name -> approuter.v1.DeleteChatAck
	12, // 8: approuter.v1.AppFrame.error:type_name -> approuter.v1.Error
	9,  // 9: approuter.v1.AppFrame.heartbeat:type_name -> approuter.v1.Heartbeat
	10, // 10: approuter.v1.AppFrame.find_app:type_name -> approuter.v1.FindApp
	11, // 11: approuter.v1.AppFrame.find_app_result:type_name -> approuter.v1.FindAppResult
	13, // 12: approuter.v1.Connect.metadata:type_name -> approuter.v1.Connect.MetadataEntry
	14, // 13: approuter.v1.StartChat.metadata:type_name -> approuter.v1.StartChat.MetadataEntry
	0,  // 14: approuter.v1.AppRouter.Open:input_type -> approuter.v1.AppFrame
	0,  // 15: approuter.v1.AppRouter.Open:output_type -> approuter.v1.AppFrame
	15, // [15:16] is the sub-list for method output_type
	14, // [14:15] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_app_router_proto_init() }
func file_proto_app_router_proto_init() {
	if File_proto_app_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_app_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppFrame); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Connect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartChatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChatMessageAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteChatAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindApp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FindAppResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_app_router_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_app_router_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*AppFrame_Connect)(nil),
		(*AppFrame_ConnectAck)(nil),
		(*AppFrame_StartChat)(nil),
		(*AppFrame_StartChatAck)(nil),
		(*AppFrame_ChatMessage)(nil),
		(*AppFrame_ChatMessageAck)(nil),
		(*AppFrame_DeleteChat)(nil),
		(*AppFrame_DeleteChatAck)(nil),
		(*AppFrame_Error)(nil),
		(*AppFrame_Heartbeat)(nil),
		(*AppFrame_FindApp)(nil),
		(*AppFrame_FindAppResult)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_app_router_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_app_router_proto_goTypes,
		DependencyIndexes: file_proto_app_router_proto_depIdxs,
		MessageInfos:      file_proto_app_router_proto_msgTypes,
	}.Build()
	File_proto_app_router_proto = out.File
	file_proto_app_router_proto_rawDesc = nil
	file_proto_app_router_proto_goTypes = nil
	file_proto_app_router_proto_depIdxs = nil
}
