// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/nodemesh.proto

package nodemeshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeMesh_Join_FullMethodName      = "/nodemesh.v1.NodeMesh/Join"
	NodeMesh_Gossip_FullMethodName    = "/nodemesh.v1.NodeMesh/Gossip"
	NodeMesh_RouteChat_FullMethodName = "/nodemesh.v1.NodeMesh/RouteChat"
)

// NodeMeshClient is the client API for NodeMesh service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NodeMesh defines node↔node contracts for membership gossip and chat routing.
type NodeMeshClient interface {
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	Gossip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipMessage], error)
	RouteChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteFrame, RouteFrame], error)
}

type nodeMeshClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeMeshClient(cc grpc.ClientConnInterface) NodeMeshClient {
	return &nodeMeshClient{cc}
}

func (c *nodeMeshClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, NodeMesh_Join_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeMeshClient) Gossip(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GossipMessage, GossipMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeMesh_ServiceDesc.Streams[0], NodeMesh_Gossip_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GossipMessage, GossipMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeMesh_GossipClient = grpc.BidiStreamingClient[GossipMessage, GossipMessage]

func (c *nodeMeshClient) RouteChat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RouteFrame, RouteFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeMesh_ServiceDesc.Streams[1], NodeMesh_RouteChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RouteFrame, RouteFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeMesh_RouteChatClient = grpc.BidiStreamingClient[RouteFrame, RouteFrame]

// NodeMeshServer is the server API for NodeMesh service.
// All implementations must embed UnimplementedNodeMeshServer
// for forward compatibility.
//
// NodeMesh defines node↔node contracts for membership gossip and chat routing.
type NodeMeshServer interface {
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	Gossip(grpc.BidiStreamingServer[GossipMessage, GossipMessage]) error
	RouteChat(grpc.BidiStreamingServer[RouteFrame, RouteFrame]) error
	mustEmbedUnimplementedNodeMeshServer()
}

// UnimplementedNodeMeshServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeMeshServer struct{}

func (UnimplementedNodeMeshServer) Join(context.Context, *JoinRequest) (*JoinResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (UnimplementedNodeMeshServer) Gossip(grpc.BidiStreamingServer[GossipMessage, GossipMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Gossip not implemented")
}
func (UnimplementedNodeMeshServer) RouteChat(grpc.BidiStreamingServer[RouteFrame, RouteFrame]) error {
	return status.Errorf(codes.Unimplemented, "method RouteChat not implemented")
}
func (UnimplementedNodeMeshServer) mustEmbedUnimplementedNodeMeshServer() {}
func (UnimplementedNodeMeshServer) testEmbeddedByValue()                  {}

// UnsafeNodeMeshServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeMeshServer will
// result in compilation errors.
type UnsafeNodeMeshServer interface {
	mustEmbedUnimplementedNodeMeshServer()
}

func RegisterNodeMeshServer(s grpc.ServiceRegistrar, srv NodeMeshServer) {
	// If the following call pancis, it indicates UnimplementedNodeMeshServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeMesh_ServiceDesc, srv)
}

func _NodeMesh_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeMeshServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NodeMesh_Join_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeMeshServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeMesh_Gossip_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeMeshServer).Gossip(&grpc.GenericServerStream[GossipMessage, GossipMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeMesh_GossipServer = grpc.BidiStreamingServer[GossipMessage, GossipMessage]

func _NodeMesh_RouteChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeMeshServer).RouteChat(&grpc.GenericServerStream[RouteFrame, RouteFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeMesh_RouteChatServer = grpc.BidiStreamingServer[RouteFrame, RouteFrame]

// NodeMesh_ServiceDesc is the grpc.ServiceDesc for NodeMesh service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeMesh_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nodemesh.v1.NodeMesh",
	HandlerType: (*NodeMeshServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _NodeMesh_Join_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Gossip",
			Handler:       _NodeMesh_Gossip_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RouteChat",
			Handler:       _NodeMesh_RouteChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/nodemesh.proto",
}
